# This is my numpy test

In [3]:
import numpy as np

# Creating arrays

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10, 3.5)

array([3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(0,10,11) # raneStart,rangeEnd,steps

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# Multi-dimentional arrays

In [ ]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
n= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
n[0,2]

np.int64(3)

In [ ]:
n[0,2] = 10

In [ ]:
n[0,2]

np.int64(10)

In [ ]:
n[2] = np.ones(3)

In [ ]:
n[2]

array([1, 1, 1])

In [ ]:
n

array([[ 1,  2, 10],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [ ]:
n[:,2] = [0,1,2]

In [ ]:
n

array([[1, 2, 0],
       [4, 5, 1],
       [1, 1, 2]])

# Radnomly generated arrays

In [ ]:
np.random.rand(5,2)

array([[0.03476087, 0.0205929 ],
       [0.78767104, 0.80215171],
       [0.42183007, 0.97834826],
       [0.05521676, 0.57701164],
       [0.05026987, 0.17870066]])

In [ ]:
np.random.seed(2) # we fix the seed such that the "random" numbers are alwyays same
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [ ]:
np.random.seed(2) # we fix the seed such that the "random" numbers are alwyays same
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [ ]:
np.random.randn(5,2)

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

# Element-wise-operations

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
a + 1

array([1, 2, 3, 4, 5])

In [ ]:
a * 2

array([0, 2, 4, 6, 8])

Linear algebra

In [ ]:
u = np.arange(5)

In [ ]:
u

array([0, 1, 2, 3, 4])

In [ ]:
v = np.arange(6,11)

In [ ]:
v

array([ 6,  7,  8,  9, 10])

In [ ]:
u + v

array([ 6,  8, 10, 12, 14])

# Vector-Vector Multiplication

Dot product $v^{T}u = \sum_{n=1}^{n} u_{i} * v_{i}$

In [ ]:
u_shape = u.shape[0]
v_shape = v.shape[0]
print(f'{u_shape} {v_shape}')

5 5


In [8]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]

    result =  0.0
    for i in range(n):
        result += u[i] * v[i]
    return result

In [ ]:
vector_vector_multiplication(u,v)

np.float64(90.0)

In [ ]:
u.dot(v)

np.int64(90)

# Matrix-Vector Multiplication
$ U = \begin{pmatrix}
2 & 4 & 5 & 6 \\
1 & 2 & 1 & 2 \\
3 & 1 & 2 & 1 \\
\end{pmatrix}, 
v = \begin{pmatrix}
1  \\
0.5 \\
2 \\
1 \\; Uv
\end{pmatrix}$

# Matrix–Vektor-Multiplikation: Definition und Beispiel

**Definition.** Sei \(A\in\mathbb{R}^{m\times n}\) mit Einträgen \(a_{ij}\) und \(\mathbf{x}\in\mathbb{R}^n\) mit Einträgen \(x_j\).
Das Produkt \(A\mathbf{x}\in\mathbb{R}^m\) ist definiert durch
$$
(A\mathbf{x})_i=\sum_{j=1}^{n} a_{ij}\,x_j \qquad (i=1,\dots,m).
$$
Äquivalent ist \(A\mathbf{x}\) eine Linearkombination der Spalten von \(A\):
$$
A\mathbf{x}=x_1\,\mathbf{a}^{(1)}+x_2\,\mathbf{a}^{(2)}+\cdots+x_n\,\mathbf{a}^{(n)},
$$
wobei \(\mathbf{a}^{(j)}\) die \(j\)-te Spalte von \(A\) ist.

**Beispiel.** Berechne \(A\mathbf{x}\) für
$$
A=\begin{bmatrix}
2 & -1 & 0\\
3 & 4 & 1\\
-2 & 5 & 2
\end{bmatrix},
\qquad
\mathbf{x}=\begin{bmatrix}1\\ 2\\ -1\end{bmatrix}.
$$

Komponentenweise:
$$
\begin{aligned}
(A\mathbf{x})_1 &= 2\cdot1 + (-1)\cdot2 + 0\cdot(-1) = 0,\\
(A\mathbf{x})_2 &= 3\cdot1 + 4\cdot2 + 1\cdot(-1) = 10,\\
(A\mathbf{x})_3 &= (-2)\cdot1 + 5\cdot2 + 2\cdot(-1) = 6.
\end{aligned}
$$

Damit
$$
A\mathbf{x}=\begin{bmatrix}0\\ 10\\ 6\end{bmatrix}.
$$


$$ 
\begin{pmatrix}
\alpha_{11} & \begin{matrix} * & \dots & * \end{matrix} \\
\begin{matrix} 0 \\ \vdots \\ 0 \end{matrix} & A_{11}
\end{pmatrix}
$$

$$ 
\begin{pmatrix}
u_{0} &  \dots & u_{n} \\
\vdots & \ddots  & \vdots \\
u_{m} &  \dots & u_{n} \\
\end{pmatrix}
\begin{pmatrix}
v_{0} \\
\vdots \\
v_{n}
\end{pmatrix}
=
\begin{pmatrix}
u_{0}^{T}v \\
\vdots \\
u_{m}^{T}v
\end{pmatrix}
$$

In [10]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])
U.shape
v = np.arange(5,8)

In [14]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]
    num_rows = U.shape[0]
    result= np.zeros(num_rows)
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i],v)
    return result
    
        
    

In [15]:
matrix_vector_multiplication(U,v)

array([117.,  40.,  43.])

In [16]:
U.dot(v)

array([117,  40,  43])

# Matrix-Matrix Multiplication
$$ 
\begin{pmatrix}
u_{0} &  \dots & u_{n} \\
\vdots & \ddots  & \vdots \\
u_{m} &  \dots & u_{n} \\
\end{pmatrix}
\begin{pmatrix}
v_{0} &  \dots & v_{l} \\
\vdots & \ddots  & \vdots \\
v_{0n}&  \dots & v_{l} \\
\end{pmatrix}
=
\begin{pmatrix}
u_{0} v_{0} & \dots & u_{m} v_{l} \\
\end{pmatrix}
$$