# This is my numpy test

In [1]:
import numpy as np

# Creating arrays

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10, 3.5)

array([3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0,10,11) # raneStart,rangeEnd,steps

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# Multi-dimentional arrays

In [14]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
n= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [16]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
n[0,2]

np.int64(3)

In [19]:
n[0,2] = 10

In [20]:
n[0,2]

np.int64(10)

In [26]:
n[2] = np.ones(3)

In [27]:
n[2]

array([1, 1, 1])

In [23]:
n

array([[ 1,  2, 10],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [28]:
n[:,2] = [0,1,2]

In [29]:
n

array([[1, 2, 0],
       [4, 5, 1],
       [1, 1, 2]])

# Radnomly generated arrays

In [33]:
np.random.rand(5,2)

array([[0.03476087, 0.0205929 ],
       [0.78767104, 0.80215171],
       [0.42183007, 0.97834826],
       [0.05521676, 0.57701164],
       [0.05026987, 0.17870066]])

In [34]:
np.random.seed(2) # we fix the seed such that the "random" numbers are alwyays same
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [35]:
np.random.seed(2) # we fix the seed such that the "random" numbers are alwyays same
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [36]:
np.random.randn(5,2)

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

# Element-wise-operations