In [8]:
# Setup: NumPy import and print versions
import numpy as np
import sys
print("NumPy version:", np.__version__)
print("Python version:", sys.version.split()[0])


NumPy version: 2.3.1
Python version: 3.12.1


In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 3.5)

array([3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.linspace(0,10,11) # raneStart,rangeEnd,steps

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
n= np.array([
[1,2,3],
[4,5,6],
[7,8,9]
])

In [11]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
n[0,2]

np.int64(3)

In [15]:
n[0,2] = 10

In [16]:
n[0,2]

np.int64(10)

In [18]:
n[2] = np.ones(3)

In [19]:
n[2]

array([1, 1, 1])

In [20]:
n

array([[ 1,  2, 10],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [21]:
 np.random.rand(5,2)

array([[0.64589851, 0.00883025],
       [0.87850149, 0.18799709],
       [0.62762251, 0.3680792 ],
       [0.4469396 , 0.08552083],
       [0.66186099, 0.94437431]])